<?php echo $this->doctype(); ?>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="images/favicon.png" type="image/png">

  <title>Xyz</title>

  <link href="<?php echo $this->basepath('adm/css/style.default.css')?> " rel="stylesheet">
  <link href="<?php echo $this->basepath('adm/css/jquery.datatables.css')?>" rel="stylesheet">
   <link href="<?php echo $this->basepath('adm/css/jquery.gritter.css')?>" rel="stylesheet">
    
  <script src="<?php echo $this->basepath('adm/js/jquery-1.10.2.min.js')?>"></script>
  <script src="<?php echo $this->basepath('adm/js/jquery-migrate-1.2.1.min.js')?>"></script>
  <script src="<?php echo $this->basepath('adm/js/jquery-ui-1.10.3.min.js')?>"></script>
  <script src="<?php echo $this->basepath('adm/js/bootstrap.min.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/jquery.datatables.min.js')?>"></script>
  <script src="<?php echo $this->basepath('adm/js/table-ok.js')?>"></script>
  
  
  
  
  

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="adm/js/html5shiv.js"></script>
  <script src="adm/js/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<!-- Preloader -->
<div id="preloader">
    <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>

<section>
  
  <div class="leftpanel">
    
    <div class="logopanel">
        <h1><span>[</span> Xyz <span>]</span></h1>
    </div><!-- logopanel -->
        
    <div class="leftpanelinner">    
        
        <!-- This is only visible to small devices -->
        <div class="visible-xs hidden-sm hidden-md hidden-lg">   
            <div class="media userlogged">
                <img alt="" src="images/photos/loggeduser.png" class="media-object">
                <div class="media-body">
                    <h4>John Doe</h4>
                    <span>"Life is so..."</span>
                </div>
            </div>
          
            <h5 class="sidebartitle actitle">Account</h5>
            <ul class="nav nav-pills nav-stacked nav-bracket mb30">
              <li><a href="profile.html"><i class="fa fa-user"></i> <span>Profile</span></a></li>
              <li><a href=""><i class="fa fa-cog"></i> <span>Account Settings</span></a></li>
              <li><a href=""><i class="fa fa-question-circle"></i> <span>Help</span></a></li>
              <li><a href="signout.html"><i class="fa fa-sign-out"></i> <span>Sign Out</span></a></li>
            </ul>
        </div>
      
      <h5 class="sidebartitle">Navegação</h5>
      <ul class="nav nav-pills nav-stacked nav-bracket">
      	<li ><a href="<?php echo $this->url('admin')?>"><i class="fa fa-home"></i> <span>Enquetes</span></a></li>
        <li ><a href="<?php echo $this->url('admin/default',array('controller'=>'index', 'action'=>'relatorio'))?>"><i class="fa fa-book"></i> <span>Relatórios</span></a></li>
        
        
      </ul>
      
      
      
    </div><!-- leftpanelinner -->
  </div><!-- leftpanel -->
  
  <div class="mainpanel">
    
    <div class="headerbar">
      
      <a class="menutoggle"><i class="fa fa-bars"></i></a>
      
      
      
      <div class="header-right">
        <ul class="headermenu">
          
          
          
          <li>
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                
                Xyz
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-usermenu pull-right">
                
                
                <li><a href="<?php echo $this->url("logout")?>"><i class="glyphicon glyphicon-log-out"></i> Sair</a></li>
              </ul>
            </div>
          </li>
          
        </ul>
      </div><!-- header-right -->
      
    </div><!-- headerbar -->
    
    <div class="pageheader">
      <h2><i class="fa fa-home"></i> XYZ </h2>
      
    </div>
    
    <div class="contentpanel">
      
      
     <?php echo $this->content; ?>
      
      
      
      
      
      
    </div><!-- contentpanel -->
    
  </div><!-- mainpanel -->
  
  <div class="rightpanel">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified">
        <li class="active"><a href="#rp-alluser" data-toggle="tab"><i class="fa fa-users"></i></a></li>
        <li><a href="#rp-favorites" data-toggle="tab"><i class="fa fa-heart"></i></a></li>
        <li><a href="#rp-history" data-toggle="tab"><i class="fa fa-clock-o"></i></a></li>
        <li><a href="#rp-settings" data-toggle="tab"><i class="fa fa-gear"></i></a></li>
    </ul>
        
    <!-- Tab panes -->
    
  </div><!-- rightpanel -->
  
  
</section>



<script src="<?php echo $this->basepath('adm/js/modernizr.min.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/jquery.sparkline.min.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/toggles.min.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/retina.min.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/jquery.cookies.js')?>"></script>

<script src="<?php echo $this->basepath('adm/js/flot/flot.min.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/flot/flot.resize.min.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/morris.min.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/raphael-2.1.0.min.js')?>"></script>

<script src="<?php echo $this->basepath('adm/js/jquery.datatables.min.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/chosen.jquery.min.js')?>"></script>

<script src="<?php echo $this->basepath('adm/js/custom.js')?>"></script>
<script src="<?php echo $this->basepath('adm/js/dashboard.js')?>"></script>

</body>
</html>