
<?php 
      $form = $this->form;
      
      $form->setAttribute('action', $this->url("auth"));
      
      $form->prepare();
      
    
      
     
     
     
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="images/favicon.png" type="image/png">

  <title>Xyz</title>

  <link href="<?php echo $this->basepath("adm/css/style.default.css")?>" rel="stylesheet">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
  <![endif]-->
</head>

<body class="signin">

<!-- Preloader -->
<div id="preloader">
    <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>

<section>
  
    <div class="signinpanel">
        
        <div class="row">
            
            <div class="col-md-3">
                
                <div class="signin-info">
                    <div class="logopanel">
                        
                    </div><!-- logopanel -->
                
                    
                
                    
                </div><!-- signin0-info -->
            
            </div><!-- col-sm-7 -->
            
            <div class="col-md-5">
            	<?php if($this->error):?>
                	<h4 style="text-align: center;">Usuário ou senha incorretos</h4>
                <?php endif;?>
                <?php echo $this->form()->openTag($form);?>
                    <h4 class="nomargin">Login</h4>
                    
                
                   
                    <?php  echo $this->formRow($form->get("email"));?>
                    <?php  echo $this->formRow($form->get("password"));?>
                    
                    <?php  echo $this->formSubmit($form->get("submit"));?>
                    
                <?php  echo $this->form()->closeTag();?>
                    
                
            </div><!-- col-sm-5 -->
            
        </div><!-- row -->
        
        <div class="signup-footer">
            <div class="pull-left">
                
            </div>
            <div class="pull-right">
                
            </div>
        </div>
        
    </div><!-- signin -->
  
</section>


<script src="<?php echo $this->basepath("adm/js/jquery-1.10.2.min.js")?>"></script>
<script src="<?php echo $this->basepath("adm/js/jquery-migrate-1.2.1.min.js")?>"></script>
<script src="<?php echo $this->basepath("adm/js/bootstrap.min.js")?>"></script>
<script src="<?php echo $this->basepath("adm/js/modernizr.min.js")?>"></script>
<script src="<?php echo $this->basepath("adm/js/retina.min.js")?>"></script>
<script src="<?php echo $this->basepath("adm/js/custom.js")?>"></script>


</body>
</html>
