<?php if($this->success):?>

<div class="alert alert-success" style="margin-top: 5px;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <?php echo $this->success[0]; ?>
</div>

<?php elseif($this->error): ?>
<div class="alert alert-danger" style="margin-top: 5px;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <?php echo $this->error[0]; ?>
</div>
<?php endif;?>

<div class="panel panel-default" >
		
		        <div class="panel-heading">
		          <div class="">
		           <a style="float: right;" href="#" class="btn btn-primary"  data-toggle="modal" data-target="#ModalTitulo"> Editar Título</a>
		            
		          </div>
		          <h4 class="panel-title"> Enquete <?php echo $this->entity->getTitulo()?></h4>
		          
		        
		        </div>
		        <div class="panel-body">
		         	 <a style="float: right; margin-bottom: 10px;" href="#" class="btn btn-primary"  data-toggle="modal" data-target="#ModalPergunta" > Nova Pergunta</a>
		         	 <div class="table-responsive">
		         	   
			            <table  class="table table-striped table-hidaction mb30 table-hover">					
								
			          		
			          		
			          		
			          			<?php foreach ($this->entity->getPerguntas() as $value):?>
			          				<tr>
			          					<td style="background-color: #f5f5f5"><?php echo $value->getPergunta()?>				          				
			          					</td>
			          					<td style="background-color: #f5f5f5" class="table-action text-center">
			          						
				                			<a href="#" title="Inserir Resposta" class=" tooltips" data-placement="top" data-toggle="modal" data-target="#ModalAdd-<?php echo $value->getId() ?>">
                    							
                    							<i class="fa  fa-plus-square"></i>
                							</a> |
				                			
				                			<a href="#" title="Editar" class=" tooltips" data-placement="top" data-toggle="modal" data-target="#ModalEdP-<?php echo $value->getId() ?>">
                    							<i class="fa  fa-edit"></i>
                							</a> |
				                						
                							<a href="#" title="Excluir" class=" tooltips" data-placement="top" data-toggle="modal" data-target="#ModalDeP-<?php echo $value->getId() ?>">
                    							<i class="fa  fa-trash-o"></i>
                							</a>
                							
                							
                							<div class="modal fade" id="ModalAdd-<?php echo $value->getId()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
													  <div class="modal-dialog">
													    <div class="modal-content">
													      <div class="modal-header">
													        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
													        <h4 class="modal-title" id="myModalLabel">Inserir Resposta</h4>
													      </div>	
													      <?php 
													      $form_resposta1 = $this->resposta;
													      
													      $form_resposta1->setAttribute('action', $this->url("admin/default", array('controller'=>'index', 'action'=>'new-resposta')));
													      
													      $form_resposta1->prepare();
													      
													      echo $this->form()->openTag($form_resposta1);
													      echo $this->formHidden($form_resposta1->get("id"));
													      echo $this->formHidden($form_resposta1->get("Perguntas_id")->setValue($value->getId()));
													      ?>
													      	
													     									      
														      <div class="modal-body" >							      		 
													              
														             
														                  <div class="form-group">
														                    <?php  echo $this->formRow($form_resposta1->get("resposta"));?>
														                    <input type="hidden" name="id_enquete" value="<?php echo $this->entity->getId()?>">
														                    
														                  </div>
															         		               
															      	  
														      </div>
													      
														      <div class="modal-footer">
														      		
																      <?php echo $this->formSubmit($form_resposta1->get("submit"));?>
																        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
																       								        			        
														    		
														      </div>
													      <?php echo $this->form()->closeTag();?>
			   
														   
													    </div>
													  </div>
												</div> 
			                						
	                							<div class="modal fade" id="ModalDeP-<?php echo $value->getId()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
													  <div class="modal-dialog">
													    <div class="modal-content">
													      <div class="modal-header">
													        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
													        <h4 class="modal-title" id="myModalLabel">Excluir Pergunta</h4>
													      </div>	
													      <form method="post" action="<?php echo $this->url("admin/default", array('controller'=>'index', 'action'=>"delete-pergunta"))?>">									      
														      <div class="modal-body" >							      		 
													              
														              Tem certeza que dejesa excluir esta Pergunta ?			               
															      	  
														      </div>
													      
														      <div class="modal-footer">
														      		
																      	<input type="hidden" name="id_pergunta" value="<?php echo $value->getId()?>">
																      	<input type="hidden" name="id_enquete" value="<?php echo $this->entity->getId()?>">
																        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
																        <button type="submit"  class="btn btn-primary" >Excluir</button>								        			        
														    		
														      </div>
													      </form>
														   
													    </div>
													  </div>
												</div> 
												
												<div class="modal fade" id="ModalEdP-<?php echo $value->getId()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
													  <div class="modal-dialog">
													    <div class="modal-content">
													      <div class="modal-header">
													        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
													        <h4 class="modal-title" id="myModalLabel">Ediatar Pergunta</h4>
													      </div>	
													      <?php 
													      $form_pergunta = $this->pergunta;
													      
													      $form_pergunta->setAttribute('action', $this->url("admin/default", array('controller'=>'index', 'action'=>'edit-pergunta')));
													      
													      $form_pergunta->prepare();
													      
													      echo $this->form()->openTag($form_pergunta);
													      echo $this->formHidden($form_pergunta->get("id")->setValue($value->getId()));
													      echo $this->formHidden($form_pergunta->get("Enquetes_id")->setValue($this->entity->getId()));
													      ?>
													      	
													     									      
														      <div class="modal-body" >							      		 
													              
														             
														                  <div class="form-group">
														                    <?php  echo $this->formRow($form_pergunta->get("pergunta")->setValue($value->getPergunta()));?>
														                    
														                  </div>
															         		               
															      	  
														      </div>
													      
														      <div class="modal-footer">
														      		
																      <?php echo $this->formSubmit($form_pergunta->get("submit"));?>
																        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
																       								        			        
														    		
														      </div>
													      <?php echo $this->form()->closeTag();?>
			   
														   
													    </div>
													  </div>
												</div> 
			          					</td>
			          				</tr>
			          				<?php foreach ($value->getRespostas() as $value2):?>
					          					<tr>
					          						<td style="background-color: white; padding-left: 50px"><?php echo $value2->getResposta()?></td>
					          						<td style="background-color: white;" class="table-action text-center">
					          							
					          							<a href="#" title="Editar" class=" tooltips" data-placement="top" data-toggle="modal" data-target="#ModalEdR-<?php echo $value2->getId() ?>">
			                    							<i class="fa  fa-edit"></i>
			                							</a> |
							                						
			                							<a href="#" title="Excluir" class=" tooltips" data-placement="top" data-toggle="modal" data-target="#ModalDeR-<?php echo $value2->getId() ?>">
			                    							<i class="fa  fa-trash-o"></i>
			                							</a>
			                							
			                							<div class="modal fade" id="ModalDeR-<?php echo $value2->getId()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
														  <div class="modal-dialog">
														    <div class="modal-content">
														      <div class="modal-header">
														        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
														        <h4 class="modal-title" id="myModalLabel">Excluir Resposta</h4>
														      </div>	
														      <form method="post" action="<?php echo $this->url("admin/default", array('controller'=>'index', 'action'=>"delete-resposta"))?>">									      
															      <div class="modal-body" >							      		 
														              
															              Tem certeza que dejesa excluir esta Resposta ?			               
																      	  
															      </div>
														      
															      <div class="modal-footer">
															      		
																	      	<input type="hidden" name="id_resposta" value="<?php echo $value2->getId()?>">
																	      	<input type="hidden" name="id_enquete" value="<?php echo $this->entity->getId()?>">
																	        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
																	        <button type="submit"  class="btn btn-primary" >Excluir</button>								        			        
															    		
															      </div>
														      </form>
															   
														    </div>
														  </div>
													</div> 
			                							
			                							
			                							<div class="modal fade" id="ModalEdR-<?php echo $value2->getId()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
														  <div class="modal-dialog">
														    <div class="modal-content">
														      <div class="modal-header">
														        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
														        <h4 class="modal-title" id="myModalLabel">Editar Resposta</h4>
														      </div>	
														      <?php 
														      $form_resposta = $this->resposta2;
														      
														      $form_resposta->setAttribute('action', $this->url("admin/default", array('controller'=>'index', 'action'=>'edit-resposta')));
														      
														      $form_resposta->prepare();
														      
														      echo $this->form()->openTag($form_resposta);
														      echo $this->formHidden($form_resposta->get("id")->setValue($value2->getId()));
														      echo $this->formHidden($form_resposta->get("Perguntas_id")->setValue($value->getId()));
														      ?>
														      	
														     									      
															      <div class="modal-body" >							      		 
														              
															             
															                  <div class="form-group">
															                    <?php  echo $this->formRow($form_resposta->get("resposta")->setValue($value2->getREsposta()));?>
															                    
															                  </div>
																         		               
																      	  
															      </div>
														      
															      <div class="modal-footer">
															      		
																	      <?php echo $this->formSubmit($form_resposta->get("submit"));?>
																	        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
																	        <input type="hidden" name="id_enquete" value="<?php echo $this->entity->getId()?>">
																	       								        			        
															    		
															      </div>
														      <?php echo $this->form()->closeTag();?>
				   
															   
														    </div>
														  </div>
														</div>
					          						
					          						</td>
					          					</tr>
					          				<?php endforeach;?>	
			          			<?php endforeach;?>
			          		
								
						
						</table>
	         	
	         		</div>
		         
		        </div><!-- panel-body -->
		        
		
	</div>
	
	
	<div class="modal fade" id="ModalTitulo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="myModalLabel">Editar Enquete</h4>
		      </div>
		      <?php 
		      $form_enquete = $this->enquete;
		      
		      $form_enquete->setAttribute('action', $this->url("admin/default", array('controller'=>'index', 'action'=>'edit-enquete')));
		      
		      $form_enquete->prepare();
		      
		      echo $this->form()->openTag($form_enquete);
		      echo $this->formHidden($form_enquete->get("id")->setValue($this->entity->getId()));
		      ?>
		      	
		     									      
			      <div class="modal-body" >							      		 
		              
			             
			                  <div class="form-group">
			                    <?php  echo $this->formRow($form_enquete->get("titulo")->setValue($this->entity->getTitulo()));?>
			                    
			                  </div>
				         		               
				      	  
			      </div>
		      
			      <div class="modal-footer">
			      		
					      <?php echo $this->formSubmit($form_enquete->get("submit"));?>
					        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
					       								        			        
			    		
			      </div>
		      <?php echo $this->form()->closeTag();?>
			   
		    </div>
		  </div>
	</div>
	
	
	<div class="modal fade" id="ModalPergunta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="myModalLabel">Inserir Pergunta</h4>
		      </div>
		      <?php 
		      $form_pergunta = $this->pergunta2;
		      
		      $form_pergunta->setAttribute('action', $this->url("admin/default", array('controller'=>'index', 'action'=>'new-pergunta')));
		      
		      $form_pergunta->prepare();
		      
		      echo $this->form()->openTag($form_pergunta);
		      echo $this->formHidden($form_pergunta->get("id"));
		      echo $this->formHidden($form_pergunta->get("Enquetes_id")->setValue($this->entity->getId()));
		      ?>
		      	
		     									      
			      <div class="modal-body" >							      		 
		              
			             
			                  <div class="form-group">
			                    <?php  echo $this->formRow($form_pergunta->get("pergunta"));?>
			                    
			                  </div>
				         		               
				      	  
			      </div>
		      
			      <div class="modal-footer">
			      		
					      <?php echo $this->formSubmit($form_pergunta->get("submit"));?>
					        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
					       								        			        
			    		
			      </div>
		      <?php echo $this->form()->closeTag();?>
			   
		    </div>
		  </div>
	</div>