<script src="<?php echo $this->basepath('adm/js/my/insert.js')?>"></script>

<div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-btns">
            
            
          </div>
          <h4 class="panel-title">Nova Enquete</h4>
          
        </div>
        <form method="post" action="<?php echo $this->url("admin/default", array('controller'=>'index', 'action'=>'new'))?>">
	        <div class="panel-body">
	         
	            
	            <div class="row" >
	            	<div class="col-sm-5 ">
			            <div class="form-group">
			              <label for="exampleInputEmail2">Título</label>
			              <input type="text" name="titulo" required="required" class="form-control verificacao" id="exampleInputEmail2" placeholder="Título da Enquete">
			            </div>
		            </div>
		            <div class="col-sm-5 " style="margin-top: 29px">
		            	<a class="btn btn-primary" id="new_help">Nova Pergunta</a>
		            </div>
		            
		        </div>
		       <div class="row" style="margin-top: 40px;" id="div_insert" ></div> 
		            
		               
	     	</div> 
		     <div class="panel-footer">
		           <button class="btn btn-primary" type="submit">Adicionar</button>
		                
		  	</div>
            
         </form>
</div>

<div style="display: none;">

	<div class="col-sm-12" style="margin-top: 30px;" id="div_perguntas">	
	       			<div class="col-sm-8 ">
			        	<div class="input-group has-warning">
		                  <input type="text" name="perguntas[]" class="form-control verificar "  required="required" placeholder="Insira a pergunta">
		                  <input type="hidden" name="hide_perguntas[]" class="hide_perguntas">
		                  <div class="input-group-btn">
		                    <button type="button" class="btn btn-primary btn_resposta" tabindex="-1" style="line-height: 26px;">Resposta</button>
	                    	<button type="button" class="btn btn-danger dropdown-toggle btn_remove" style="line-height: 26px;" data-toggle="dropdown" tabindex="-1">
		                      X
		                    </button>
		                    
		                  </div>
		                </div>                  
		                
	                  
	                </div>
	</div> 
	
	
	
	<div class="row" style="margin-top: 5px;" id="div_respostas" >
	     <div class="col-sm-11 " style="float: right !important;" >
		      <div class="input-group has-success">
	                  <input type="text" class="form-control verificar" name="respostas[]"  required="required" placeholder="Insira a resposta">
	                  <input type="hidden" name="hide_respostas[]" class="hide_respostas">
	                  <div class="input-group-btn">
	                    
	                    <button type="button" class="btn btn-danger dropdown-toggle btn_remove" style="line-height: 26px;" data-toggle="dropdown" tabindex="-1">
			                      X
			            </button>
			                    
			        </div>
			  </div>               
	                  
	     </div>
	 </div> 
</div> 


<div class="modal fade" id="ModalVeri" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="myModalLabel">Alerta</h4>
		      </div>	
		      									      
			      <div class="modal-body" >							      		 
		              
			              Nenhum campo pode ficar em branco			               
				      	  
			      </div>
		      
			      <div class="modal-footer">
			      		
					      	
					        <button type="button" class="btn btn-danger" data-dismiss="modal">OK</button>
					        							        			        
			    		
			      </div>
		      
			   
		    </div>
		  </div>
	</div> 
 
