<?php 
      $form = $this->form;
      
      $form->setAttribute('action', $this->url("admin/default", array('controller'=>'index', 'action'=>'relatorio')));
      
      $form->prepare();
      
    
      
     
     
     
?>

<div class="panel panel-default" >
		
		        <div class="panel-heading">
		          <div class="panel-btns">
		           
		            <a href="" class="minimize">−</a>
		          </div>
		          <h4 class="panel-title">Relatório</h4>
		          
		        </div>
		        <?php   echo $this->form()->openTag($form);?>
		        <div class="panel-body">
		         	 <div class="col-sm-6 margin_top_10">
					         <div class="form-group">
				                  	<?php  echo $this->formRow($form->get("enquete"));?>
				             </div>
				       </div>
		         	 
		         
		        </div><!-- panel-body -->
		        <div class="panel-footer">
		        	<?php  echo $this->formSubmit($form->get("submit"));?>
		        </div>
		        
		        <?php  echo $this->form()->closeTag();?>
		        
		
	</div>
	
	
	
<?php if($this->enquete):?>

<div class="panel panel-default" >
		
		        <div class="panel-heading">
		          <div class="panel-btns">
		           
		            <a href="" class="minimize">−</a>
		          </div>
		          <h4 class="panel-title"><?php echo $this->enquete['titulo']?></h4>
		          
		        </div>
		        
		        <div class="panel-body">
		         	 
		         	 <?php foreach ($this->enquete['perguntas'] as $key => $value):?>
		         		<div class="col-sm-12">
		         			<h4><?php echo $value['pergunta']?> </h4>
		         			<?php foreach ($value['respostas'] as $key2=>$resposta):?>
			         			
			         			<?php 
			         			if($value['qtd_voto'] >0):
			         				$numero = number_format(($resposta->getNumero() * 100) /$value['qtd_voto'], 2, '.', '');
			         			else:
			         			$numero = 0;
			         			endif;
			         			?>
			         			<div class="col-sm-8">	
			         				<span class="sublabel"><?php echo $resposta->getResposta()?> (<?php echo $resposta->getNumero()?> / <?php echo $value['qtd_voto']?> - <?php echo $numero."%"    ?>)</span>
			         				<div class="progress progress-sm">
					                    <div style="width: <?php echo $numero ?>%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" class="progress-bar progress-bar-primary"></div>
					                 </div>
					            </div>
		         				
		         			<?php endforeach;?>
		         		</div>	
		         	 
		         	<?php endforeach;?>
		        </div><!-- panel-body -->
		        
		        
		    
		        
		
</div>



<?php endif;?>